config/routes.rb
CoffeeCoopProject::Application.routes.draw do
  resources :users

    
  resources :centers do
    resources :producers do
      resources :transactions
    end
    resources :transactions
  end
  resources :producers do
    resources :transactions
  end
  resources :transactions

  #rack-offline path
 # match "/application.manifest" => Rails::Offline
  
  # Set up Omniauth paths
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  
  match '/signin' => 'sessions#signin'
  match '/signout' => 'sessions#signout'
  

  
  scope "/:locale" do
    resources :transactions
    resources :users
  end

  resources :sessions, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'failure'
    end
  end
  

  
  match '/:locale' => 'users#index'
  
  match '/' => 'home#index'
  root :to => 'home#index'

end

app/models/center.rb
class Center < ActiveRecord::Base
  has_many :users
  has_many :transactions

  attr_accessible :name
  
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  # GET /centers
  # GET /centers.json
  def index
    @centers = Center.all
    @is_admin = user_is_admin?
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @centers }
    end
  end

  # GET /centers/1
  # GET /centers/1.json
  def show
    @center = Center.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @center }
    end
  end

  # GET /centers/new
  # GET /centers/new.json
  def new
    @center = Center.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @center }
    end
  end

  # GET /centers/1/edit
  def edit
    @center = Center.find(params[:id])
    @is_admin = user_is_admin?
  end

  # POST /centers
  # POST /centers.json
  def create
    @center = Center.new(params[:center])

    respond_to do |format|
      if @center.save
        format.html { redirect_to center_path(@center), notice: 'Center was successfully created.' }
        format.json { render json: @center, status: :created, location: @center }
      else
        format.html { render action: "new" }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /centers/1
  # PUT /centers/1.json
  def update
    @center = Center.find(params[:id])

    respond_to do |format|
      if @center.update_attributes(params[:center])
        format.html { redirect_to @center, notice: 'Center was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centers/1
  # DELETE /centers/1.json
  def destroy
    @center = Center.find(params[:id])
    @center.destroy

    respond_to do |format|
      format.html { redirect_to centers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/views/centers/_form.html.haml
= form_for @center do |f|
  -if @center.errors.any?
    #error_explanation
      %h2= "#{pluralize(@center.errors.count, "error")} prohibited this center from being saved:"
      %ul
        - @center.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label t(:name)
    = f.text_field :name

  .actions
    = f.submit t(:save)

app/views/centers/edit.html.haml
%h1= t(:edit_center)

= render 'form'

= link_to t(:show), @center, :class => 'btn'
= link_to t(:back), centers_path, :class => 'btn btn-edit'
- if @is_admin
  = link_to t(:destroy), center_path, :confirm => 'Are you sure?', :method => 'delete', :class => 'btn btn-delete'

app/views/centers/index.html.haml
%div.span
  %h1= t :centers

  %table{:class => 'table table-bordered table-striped table-condensed row-linked'}
    %tr
      %th= t(:name)
      %th= t(:producer)
      %th= t(:transactions)
      - if @is_admin
        %th= t(:options)

    - @centers.each do |center|
      %tr
        %td= center.name
        %td= link_to t(:producers), center_producers_path(center), :class => 'btn btn-small'
        %td= link_to t(:transactions), center_transactions_path(center), :class => 'btn btn-small'
        - if @is_admin
          %td= link_to t(:edit), edit_center_path(center), :class => 'btn btn-small btn-edit'

  %br
  - if @is_admin
    = link_to t(:new_center), new_center_path, :class => 'btn btn-new'

app/views/centers/new.html.haml
%h1= t(:new_center)

= render 'form'

= link_to t(:back), centers_path

app/views/centers/show.html.haml
%p#notice= notice


= link_to t(:edit), edit_center_path(@center)
\|
= link_to t(:back), centers_path