config/routes.rb
CoffeeCoopProject::Application.routes.draw do
  resources :users

    
  resources :centers do
    resources :producers do
      resources :transactions
    end
    resources :transactions
  end
  resources :producers do
    resources :transactions
  end
  resources :transactions

  #rack-offline path
 # match "/application.manifest" => Rails::Offline
  
  # Set up Omniauth paths
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  
  match '/signin' => 'sessions#signin'
  match '/signout' => 'sessions#signout'
  

  
  scope "/:locale" do
    resources :transactions
    resources :users
  end

  resources :sessions, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'failure'
    end
  end
  

  
  match '/:locale' => 'users#index'
  
  match '/' => 'home#index'
  root :to => 'home#index'

end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  def index 
    @is_admin = user_is_admin?
    if params[:center_id]
      @has_center = true
      @center = Center.find_by_id(params[:center_id])
      @producers = User.find(:all, :conditions => {:role => 'producer', :center => @center.name})
    else
      @has_center = false
      @producers = User.find_all_by_role('producer')
    end

  end 
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/index.html.haml
%div.span
  - if @has_center
    %h1 #{@center.name}'s #{t :producers}
  - else
    %h1= t :producers

  %table{:class => 'table table-bordered table-striped table-condensed row-linked'}
    %tr
      %th= t :name
      %th= t :email
      %th= t :center
      %th= t :options

    - @producers.each do |producer|
      %tr
        %td= link_to "#{producer.name}", producer
        %td= producer.email
        %td= producer.center
        %td
          = link_to t(:transactions), producer_transactions_path(producer), :class => 'btn btn-small'
          = link_to t(:show), producer, :class => 'btn btn-small'
          - if @is_admin
            = link_to t(:edit), edit_user_path(producer), :class => 'btn btn-edit btn-small'


  - if @is_admin
    =link_to t(:new_user), new_user_path, :class => 'btn btn-new'