config/routes.rb
CoffeeCoopProject::Application.routes.draw do
  resources :users

    
  resources :centers do
    resources :producers do
      resources :transactions
    end
    resources :transactions
  end
  resources :producers do
    resources :transactions
  end
  resources :transactions

  #rack-offline path
 # match "/application.manifest" => Rails::Offline
  
  # Set up Omniauth paths
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  
  match '/signin' => 'sessions#signin'
  match '/signout' => 'sessions#signout'
  

  
  scope "/:locale" do
    resources :transactions
    resources :users
  end

  resources :sessions, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'failure'
    end
  end
  

  
  match '/:locale' => 'users#index'
  
  match '/' => 'home#index'
  root :to => 'home#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
  # Display Table of Transactions
  # To Do: Set up Sorting Functionality
  def index
    options = Hash.new
    if(params[:id]) 
      options[:order] = params[:id]
    end
    session[:params] = params
    conditions = Hash.new
    if(params[:center_id])
      @center = Center.find_by_id(params[:center_id])
      unless @center.nil?
        conditions[:center] = @center.name
      end
    end
    if(params[:producer_id])
      @producer = User.find_by_id(params[:producer_id])
      unless @producer.nil?
        conditions[:producer] = @producer.name
      end
    end


    # If there is a :cooperative_id, center_id, or producer_id then filter
    # the possible options based on that.

    @transactions = Transaction.find(:all,options, :conditions => conditions)
    @can_edit = user_is_admin?  # In case we want to set up so certain non-admins can edit

    if params[:producer_id]
      @has_producer = true
      @trans_producer = User.find_by_id(params[:producer_id])
    else
      @has_producer = false
      if params[:center_id]
        @has_center = true
        @trans_center = Center.find_by_id(params[:center_id])
      else
        @has_center = false
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # Display Details for a Transaction
  # To Do: Set up editing, if clerk owns it or if admin
  def show
    @transaction = Transaction.find(params[:id])
    @can_edit = user_is_admin? 

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # New Transaction
  # To Do: Restrict lists of producers by Cooperative
  # Maybe instead of New Transaction button, have drop down for New Transaction for a specific Cooperative
  def new
    @transaction = Transaction.new
    @producers = User.find_all_by_role('producer')
    @centers = Transaction.get_centers
    @delivery_forms = Transaction.get_delivery_forms

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
    @producers = User.find_all_by_role('producer')
    @centers = Transaction.get_centers
    @delivery_forms = Transaction.get_delivery_forms
    @can_destroy = user_is_admin?

  end

  # POST /transactions
  # POST /transactions.json
  def create
    # Method to add Producer to hash to create transaction
    user = User.find_by_id(params[:transaction][:producer])
    hash = Hash.new
    hash = params[:transaction]
    @transaction = Transaction.new
    if user.nil?
      respond_to do |format|
        format.html { render action: "new" }
        format.json { head :no_content, status: :unprocessable_entity }
      end
    else
      hash[:producer] = user.name
      @transaction = user.transactions.build(hash)
      @transaction.save!
      user.save!
    
    
      respond_to do |format|
        if @transaction.save
          format.html { redirect_to @transaction, notice: t(:transaction_created) }
          format.json { render json: @transaction, status: :created, location: @transaction }
        else
          format.html { render action: "new" }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: t(:transaction_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
%section#transactions_form

%div.row-fluid

  = form_for @transaction do |f|
    -if @transaction.errors.any?
      #error_explanation
        %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
        %ul
          - @transaction.errors.full_messages.each do |msg|
            %li= msg
    
    %div.span3
      .field
        = f.label t :producer
        = f.collection_select :producer, @producers, :id, :name
      .field
        = f.label t :code
        = f.text_field :code
      .field
        = f.label t :center
        = f.select :center, @centers
      .field
        = f.label t :date
        = f.date_select :date, {:use_month_names => [t(:jan), t(:feb), t(:mar), t(:apr), t(:may), t(:jun), t(:jul), t(:aug), t(:sep), t(:oct), t(:nov), t(:dec)], :order => [:month, :day, :year]}
      .field
        = f.label t :time
        = f.time_select :date, :ampm => true

    %div.span2
      .field
        = f.label t :lot_number
        = f.number_field :lot_number, :class => 'input-small'
      .field
        = f.label t :sack
        = f.number_field :sack_number, :class => 'input-small'
      .field
        = f.label t :gweight
        = f.number_field :gross_weight, :class => 'input-small'
      .field
        = f.label t :tare
        = f.number_field :tare, :class => 'input-small'
      .field
        = f.label t :nweight
        = f.number_field :net_weight, :class => 'input-small'
      .field
        = f.label t :quality
        = f.text_field :quality, :class => 'input-small'
      .field
      = f.label t :classes
      = f.text_field :classes, :class => 'input-small'
   

    %div.span2
      .field
        = f.label t :s_f
        = f.number_field :s_f, :class => 'input-small'
      .field
        = f.label t :bitten
        = f.number_field :bitten, :class => 'input-small'
      .field
        = f.label t :bare
        = f.number_field :bare, :class => 'input-small'
      .field
        = f.label t :green
        = f.number_field :green, :class => 'input-small'
      .field
        = f.label t :drill
        = f.number_field :drill, :class => 'input-small'
      .field
        = f.label t :mold
        = f.number_field :mold, :class => 'input-small'
      .field
        = f.label t :gqmd
        = f.number_field :gqmd, :class => 'input-small'

    %div.span3
      .field
        = f.label t :price
        = f.number_field :price
      .field 
        = f.label t :comments
        = f.text_area :comments
      .field
        = f.label t :delivery_form
        = f.select :delivery_form, @delivery_forms
      .field
        = f.label t :received
        = f.text_field :received_by
      .actions
        = f.submit t :save

app/views/transactions/edit.html.haml
%h1= t(:edit_trans)

= render 'form'

= link_to t :show, @transaction, :class => 'btn '
= link_to t :back, transactions_path, :class => 'btn'
- if @can_destroy
  = link_to t :destroy, transaction_path, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-delete'

app/views/transactions/index.html.haml
%div.span
  - if @has_producer
    %h1 #{@trans_producer.name}'s #{t :transactions}
  - else
    - if @has_center
      %h1 #{@trans_center.name}'s #{t :transactions}
    -else
      %h1= t :transactions


  %table{:class => 'table table-bordered table-striped table-condensed row-linked'}
    %tr
      %th= link_to t(:receipt), transactions_path(:id => "id"), :id => "receipt_header"
      %th= link_to t(:producer), transactions_path(:id => "producer"), :id => "producer_header"
      %th= link_to t(:code), transactions_path(:id => "code"), :id => "code_header"
      %th= link_to t(:date), transactions_path(:id => "date"), :id => "date_header"
      %th= link_to t(:time), transactions_path(:id => "date"), :id => "time_header"
      %th= link_to t(:center), transactions_path(:id => "center"), :id => "center_header"
      %th= link_to t(:price), transactions_path(:id => "price"), :id => "price_header"
      %th= link_to t(:comments), transactions_path(:id => "comments"), :id => "comments_header"
      %th= link_to t(:received_by), transactions_path(:id => "producer"), :id => "producer_header"
      %th= t :options

    - @transactions.each do |transaction|
      %tr
        %td= "%04d" % transaction.id
        %td= transaction.producer
        %td= transaction.code
        %td= transaction.date.strftime("%d/%m/%y") unless transaction.date.nil?
        %td= transaction.date.strftime("%l:%M %p") unless transaction.date.nil?
        %td= transaction.center
        %td= transaction.price
        %td= transaction.comments
        %td= transaction.received_by
        %td
          = link_to t(:show), transaction, :class => 'btn btn-small'
          - if @can_edit
            = link_to t(:edit), edit_transaction_path(transaction), :class => 'btn btn-small btn-edit'

  = link_to t(:new_trans), new_transaction_path, :class => 'btn btn-new'

app/views/transactions/new.html.haml
%h1= t(:new_trans)

= render 'form'

= link_to t(:back), transactions_path, :class => 'btn'

app/views/transactions/show.html.haml
%h1 #{t :transaction} ##{@transaction.id} Info

%div.row 
  %div.span8
    %h3= t :receipt_info
    %table{:class => 'table table-condensed table-bordered'}
      %tr
        %th= t :receipt
        %th= t :producer
        %th= t :code
        %th= t :center
        %th= t :date
        %th= t :time
      %tr
        %td= @transaction.id
        %td= @transaction.producer
        %td= @transaction.code
        %td= @transaction.center
        %td= @transaction.date.strftime("%d/%m/%y") unless @transaction.date.nil?
        %td= @transaction.date.strftime("%l:%M %p") unless @transaction.date.nil?

%div.row
  %div.span8
    %h3= t :traits
    %table{:class => 'table table-condensed table-bordered'}
      %tr
        %th= t :lot
        %th= t :sack
        %th= t :gweight
        %th= t :tare
        %th= t :nweight
        %th= t :quality
        %th= t :classes
      %tr
        %td= @transaction.lot_number
        %td= @transaction.sack_number
        %td= @transaction.gross_weight
        %td= @transaction.tare
        %td= @transaction.net_weight
        %td= @transaction.quality
        %td= @transaction.classes
%div.row
  %div.span8
    %h3 Quality:
    %table{:class => 'table table-condensed table-bordered'}
      %tr
        %th= t :s_f
        %th= t :bitten
        %th= t :bare
        %th= t :green
        %th= t :drill
        %th= t :mold
        %th= t :gqmd
        %th= t :total_quality
      %tr
        %td= @transaction.s_f
        %td= @transaction.bitten
        %td= @transaction.bare
        %td= @transaction.green
        %td= @transaction.drill
        %td= @transaction.mold
        %td= @transaction.gqmd
        %td= @transaction.total

%div.row
  %div.span8
    %h3 Delivery Info:
    %table{:class => 'table table-condensed table-bordered'}
      %tr
        %th Price
        %th Delivery Form
        %th Comments
        %th Received By
      %tr
        %td= @transaction.price
        %td= @transaction.delivery_form
        %td= @transaction.comments
        %td= @transaction.received_by
- if @can_edit
  = link_to 'Edit', edit_transaction_path(@transaction), :class => 'btn btn-edit'
= link_to 'Back', transactions_path, :class => 'btn'