config/routes.rb
CoffeeCoopProject::Application.routes.draw do
  resources :users

    
  resources :centers do
    resources :producers do
      resources :transactions
    end
    resources :transactions
  end
  resources :producers do
    resources :transactions
  end
  resources :transactions

  #rack-offline path
 # match "/application.manifest" => Rails::Offline
  
  # Set up Omniauth paths
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  
  match '/signin' => 'sessions#signin'
  match '/signout' => 'sessions#signout'
  

  
  scope "/:locale" do
    resources :transactions
    resources :users
  end

  resources :sessions, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'failure'
    end
  end
  

  
  match '/:locale' => 'users#index'
  
  match '/' => 'home#index'
  root :to => 'home#index'

end

app/views/layouts/_not_signed_in.html.erb
<li>Sign In Using:</li>
<li id="imglink"><%= link_to image_tag("google_32.png", :size => "32x32", :alt => "Google"), "auth/google", :class=>"imgnav" %></li>
<% if false %>
  <li id="imglink"><%= link_to image_tag("facebook_32.png", :size => "32x32", :alt => "Facebook"), "auth/facebook", :class=>"imgnav" %></li>
  <li id="imglink"><%= link_to image_tag("twitter_32.png", :size => "32x32", :alt => "Twitter"), "auth/facebook", :class=>"imgnav" %></li>
<% end %>

app/views/layouts/_signed_in.html.erb
<li><%= link_to "#{current_user.name}", user_path(current_user) %></li>
<li><%= "#{current_user.role.capitalize}" %></li>
<li><%= link_to "Sign Out", signout_sessions_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html manifest="/application.manifest">
<head>
  <title>CoffeeCoopProject</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= javascript_include_tag :defaults, "jquery.tmpl" %>
        <link rel="shortcut icon" href"/favicon.ico" />
          <%= csrf_meta_tags %>
          </head>
          <body>
            <div id="navigation">
              <nav id="nav_bar">
                <ul>
                  <li id="logo"><%=link_to "Coffee Trail", root_path, :class => "usersnav"%></li>
                  <li id="tab"><%= link_to "#{t :centers}", centers_path, :class => "cooperativesnav"%></li>
                  <li id="tab"><%= link_to "#{t :producers}", producers_path, :class => "producersnav"%></li>
                  <li id="tab"><%= link_to "#{t :users}", users_path, :class => "usersnav"%></li>
                  <li id="tab"><%= link_to "#{t :transactions}", transactions_path, :class => "transactionsnav"%></li>
                </ul>
                <ul id="user_info">
                  <li class="languages" id="imglink"><%=link_to image_tag("english.png", :size => "32x16"), params.merge(:locale => 'en')%></li>
                  <li class="languages" id="imglink"><%=link_to image_tag("spain-flag.png", :height=>"16", :width=>"32"), params.merge(:locale => 'es')%></li>
                  <% if user_signed_in? %>
                    <%= render :partial => 'layouts/signed_in' %>
                  <% else %>
                    <%= render :partial => 'layouts/not_signed_in' %>
                  <% end %>
                </ul>
              </nav>
            </div>

          <% flash.each do |key, value| %>
            <div class="alert alert-block alert-<%= key == :notice ? "success" : key %> fadeout" data-dismiss="alert">
              <strong><%= key.capitalize %>: </strong>
              <%= value %>
              <a class="close">&times;</a>
            </div>
          <% end %>
          <div class="container-fluid">
            <div class="row-flud">
              <%= yield %>
            </div>
          </div>
    </body>
</html>